language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

install:
  - "pip install nose"
  - "pip install coveralls"
  - "pip install git+git://github.com/TurboGears/Ming.git"
  - "pip install git+https://github.com/toscawidgets/tw2.core.git@develop#egg=tw2.core"
  - "pip install git+https://github.com/toscawidgets/tw2.forms.git@develop#egg=tw2.forms"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -e .[testing_mongodb]; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -e .[testing_mongodb]; fi
  - "pip install -e .[testing]"

script: "nosetests -v --with-coverage --cover-package=sprox --cover-erase"

after_success:
  coveralls
