
name: run-tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nose
          pip install coverage
          pip install git+git://github.com/TurboGears/Ming.git
          pip install git+https://github.com/toscawidgets/tw2.core.git@develop#egg=tw2.core
          pip install git+https://github.com/toscawidgets/tw2.forms.git@develop#egg=tw2.forms
          pip install -U --upgrade-strategy=eager --pre -e .[testing]
      - name: Run Tests
        run: |
          nosetests -v --with-coverage --cover-package=sprox --cover-erase
      - name: Publish to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install 'coveralls'
          coveralls --service=github